export { PrismaClient, Prisma } from '@prisma/client';
export type {
  Tenant,
  Branch,
  User,
  Employee,
  Role,
  Permission,
  RolePermission,
  RefreshToken,
  Vehicle,
  Driver,
  Client,
  Contract,
  Route,
  RoutePoint,
  Trip,
  TripPassenger,
  Occurrence,
  FuelStation,
  FuelRecord,
  MaintenanceOrder,
  MaintenanceItem,
  Document,
  Notification,
  AuditLog,
  OutboxEvent,
  IdempotencyKey,
} from '@prisma/client';
